version: '3'

networks:
  drupal:
    driver: bridge

services:
  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d:delegated
      - ./etc/local-db:/var/lib/mysql:delegated
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    restart: always
    networks:
        - drupal

  nginx:
    image: nginx:latest
    working_dir: /var/www/html/docroot
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: fpm
      NGINX_SERVER_ROOT: /var/www/html/docroot
    ports:
      - "${APP_PORT}:80"
    links:
      - db:${APP_URL}
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:delegated
      - ./docroot:/var/www/html/docroot:delegated
    networks:
        - drupal

  fpm:
    # image: php:7.2-fpm
    build: ./etc/docker/php-fpm
    env_file: .env
    working_dir: /var/www/html/docroot
    environment: 
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    expose:
      - 9000
    links:
      - db:${APP_URL}
    volumes:
      - ./etc/php/config.ini:/usr/local/etc/php/conf.d/x-config.ini:delegated
      - ./.:/var/www/html:delegated
    networks:
        - drupal

  memcached:
    image: memcached:1.5.2-alpine
    networks:
        - drupal

  # mailhog:
  #   image: mailhog/mailhog
  #   networks:
  #       - drupal

volumes:
  local-db:
